# Generated by Django 3.1 on 2020-08-09 15:12

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimRaAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rideTimestamp', models.DateTimeField()),
                ('bikeType', models.IntegerField()),
                ('childCheckbox', models.BooleanField()),
                ('trailerCheckbox', models.BooleanField()),
                ('pLoc', models.IntegerField()),
                ('incident', models.IntegerField()),
                ('iType', models.IntegerField()),
                ('scary', models.BooleanField()),
                ('desc', models.TextField()),
                ('filename', models.CharField(max_length=32)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=32)),
                ('fileType', models.CharField(max_length=32)),
                ('importTimestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('filename', models.CharField(max_length=32)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
