# Generated by Django 3.1 on 2020-09-12 15:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimRaAPI', '0002_incident_parsedfiles_ride'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpatialData',
        ),
        migrations.AddField(
            model_name='ride',
            name='legs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
    ]
