# Generated by Django 3.1 on 2020-09-13 15:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimRaAPI', '0003_auto_20200912_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsmLargeJunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('count', models.IntegerField(default=0)),
                ('totalDuration', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OsmWaysJunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='OsmWaysLegs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osmId', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('streetName', models.TextField()),
                ('postalCode', models.TextField()),
                ('highwayName', models.TextField()),
                ('count', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('weekdayCount', models.IntegerField(default=0)),
                ('rushhourCount', models.IntegerField(default=0)),
            ],
        ),
    ]
